# -*- coding: utf-8 -*-
"""Parkinsons.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OSqOAeLC0DhGeZXfFpysHkPLN3AHAjcP
"""

#Importing Modules 

import numpy as np
import pandas as pd
import os, sys 

from sklearn.preprocessing import MinMaxScaler 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score

from xgboost import XGBClassifier

#Reading the dataset 

data = pd.read_csv('parkinsons.data')
#data.head()

#Extracting the Features 

feat = data.loc[:,data.columns != 'status'].values[:,1:]
labels = data.loc[:,'status'].values 

#print(labels[labels==1].shape[0], labels[labels==0].shape[0])

#Initializing the Scaler 

scaler = MinMaxScaler((-1,1))
x = scaler.fit_transform(feat)
y = labels

# Splitting the dataset into Trarining and Test Sets 

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

#Initializing the XGBClassifier and Training the Model 

model = XGBClassifier()
model.fit(X_train, y_train)

#Predicting the values for Test Set 

y_pred = model.predict(X_test)

#Checking the Accuracy of the Model 

print(round(accuracy_score(y_test, y_pred)*100,2))